[package]
name = "tetris"
version = "0.1.0"
authors = ["HoodleWoodle <hoodlewoodle@web.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5"